### ISSUE TITLE
Runtime Lua loading problem in native Windows build

### ISSUE THREAD

**Issue by jpy-luke** [menu-hanke/m2#3]
When cross-compiling for Windows, using mingw, on a Linux host
`make CROSS=x86_64-w64-mingw32- TARGET_SYS=Windows dependencies`
`make CC=x86_64-w64-mingw32-gcc OS=Windows XBCLFLAGS="-o windows" DEPS_LUAJIT=/usr/bin/luajit`
will run succesfully.

The produced executable however, when run on a Windows host, will produce the following error:

```
$ ./m2.exe
Lua error: failed to load embedded bytecode: =bcloader/install
stack traceback:
[C]: at 0x7ffa56327ff0
[C]: at 0x7ffa5037b780
```

The test situation had the produced m2.exe, m2.dll and lua51.dll in the working directory.

I traced this error into the usage of the -L flag in bcloader. How do we debug this further?

**Comment by vfprintf** [comment]
This is caused by bytecode incompatibility between luajit versions (namely, the older version installed in `/usr/bin` and the newer included in m2 as a submodule).

Suggested fix:
```diff
diff --git a/m2-builder/Dockerfile b/m2-builder/Dockerfile
index b48eb17..27f0cc6 100644
--- a/m2-builder/Dockerfile
+++ b/m2-builder/Dockerfile
@@ -33,7 +33,7 @@ RUN cp /work/linux/m2/src/m2 .
 #Build for Windows
 WORKDIR /work/windows/m2
 RUN make CROSS=x86_64-w64-mingw32- TARGET_SYS=Windows dependencies
-RUN make CC=x86_64-w64-mingw32-gcc OS="Windows" XBCLFLAGS="-o windows" DEPS_LUAJIT=/usr/bin/luajit
+RUN make CC=x86_64-w64-mingw32-gcc OS="Windows" XBCLFLAGS="-o windows" DEPS_LUAJIT=/work/linux/m2/deps/LuaJIT/src/luajit
 WORKDIR /work/windows/release
 RUN cp {/work/windows/m2/deps/LuaJIT/src/lua51.dll,/work/windows/m2/src/m2.exe,/work/windows/m2/src/m2.dll} .
```

**Comment by jpy-luke** [comment]
Thank you for the pointer. This does the trick. I only now realized that the latest release 2.1.0-beta3 is over four years old...
Might as well remove that from the base build image too.
